[package]
name = "kobra"
version = "2.0.0"
edition = "2021"

[[bin]]
name = "kobra"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "cookies", "gzip", "stream"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
url = "2"
regex = "1"
anyhow = "1"
rand = "0.8"
base64 = "0.21"
sha2 = "0.10"
chromiumoxide = { version = "0.7", features = ["tokio-runtime"] }
futures-util = "0.3"
